name: Apple Music - /usr/share
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.music.playlist.svg
  token: NOT_NEEDED
  base: ""
  plugin_music: yes
  plugin_music_playlist: https://embed.music.apple.com/es/playlist/usr-share/pl.u-oZylD0aFGa0N3NK
  plugin_music_limit: 4
